files:
  - source: /docs/community/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/community/%original_file_name%
  - source: /docs/dev/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/dev/%original_file_name%
  - source: /docs/instruction/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/instruction/%original_file_name%
  - source: /docs/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/%original_file_name%
  - source: /docs/dev/plugin/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/dev/plugin/%original_file_name%
