files:
  - source: /docs/community/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/community/%original_file_name%
  - source: /docs/dev/**/*
    translation: /docs/%two_letters_code%/dev/%original_file_name%
  - source: /docs/instruction/**/*
    translation: /docs/%two_letters_code%/instruction/%original_file_name%
  - source: /docs/about.md
    translation: /docs/%two_letters_code%/about.md
